general:
  version: 2.0.2
  links:
    direct: '/system/herherkerker.apk'
    google: https://play.google.com/store/apps/details?id=com.tectual.herherkerker&hl=en
    cando: http://cando.asr24.com/app.jsp?id=2262589
    bazar: http://cafebazaar.ir/app/com.tectual.herherkerker/?l=en
    myket: http://myket.ir/appdetail.aspx?id=com.tectual.herherkerker
    plaza: http://www.plazza.ir/app/9684/
  mobile:
    jokes_limit: 10
    ads_interval: 5 #hours
  report:
    date: report_last_check_date
    categories:
      users:
        total: users
        daily: daily_users
        inactive: inactive_users
      sessions:
        total: sessions
        daily: daily_sessions
development:
  profiling:
    questions:
      name: 1
      gender: 3
      email: 
      phone: 
      likes: 2
      age: 2
test:
production:
  profiling:
    questions:
      name: 1
      gender: 3
      email: 
      phone: 
      likes: 4
      age: 2
